### ISSUE TITLE
test_preprocess.py fails on Mac M1 with TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-gnn-2#74]
If I run locally test_preprocess.py on my Mac, it fails:
`FAILED tests/test_preprocess.py::test_preprocess - TypeError: cannot pickle 'module' object`. Maybe issue #56 could solve it, but we need to further investigate it.

**Comment by cbaakman** [comment]
Do you have a stack trace?

**Comment by gcroci2** [comment]
> Do you have a stack trace?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/3D-Vac/notebooks/1.0GC-pytorch_exploration.ipynb Cell 2' in <cell line: 5>()
      1 metrics_output_directory = "./metrics"
      2 metrics_exporters = [OutputExporter(metrics_output_directory),
      3                      ScatterPlotExporter(metrics_output_directory, 5)]
----> 5 nn = NeuralNet(database, GINet,
      6                node_feature=['type', 'polarity', 'bsa',
      7                              'depth', 'hse', 'ic', 'pssm'],
      8                edge_feature=['dist'],
      9                target='irmsd',
     10                index=range(400),
     11                batch_size=64,
     12                percent=[0.8, 0.2],
     13                metrics_exporters=metrics_exporters)
     15 nn.train(nepoch=50, validate=False)

File ~/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/NeuralNet.py:116, in NeuralNet.__init__(self, database, Net, node_feature, edge_feature, target, lr, batch_size, percent, database_eval, index, class_weights, task, classes, threshold, pretrained_model, shuffle, cluster_nodes, transform_sigmoid, metrics_exporters)
    114         print("the threshold for accuracy computation is set to 0.3")
    115         self.threshold = 0.3
--> 116     self.load_model(database, Net, database_eval)
    118 else:
    119     self.load_params(pretrained_model)

File ~/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/NeuralNet.py:197, in NeuralNet.load_model(self, database, Net, database_eval)
    193 train_dataset, valid_dataset = DivideDataSet(
    194     dataset, percent=self.percent)
    196 # dataloader
--> 197 self.train_loader = DataLoader(
    198     train_dataset, batch_size=self.batch_size, shuffle=self.shuffle
    199 )
    200 print("Training set loaded")
    202 if self.percent[1] > 0.0:

File ~/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch_geometric/deprecation.py:13, in deprecated.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
     10 out = f"'{func_name or func.__name__}' is deprecated" + (
     11     f', {details}' if details is not None else '')
     12 warnings.warn(out)
---> 13 return func(*args, **kwargs)

File ~/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py:78, in DataLoader.__init__(self, dataset, batch_size, shuffle, follow_batch, exclude_keys, **kwargs)
     75 self.follow_batch = follow_batch
     76 self.exclude_keys = exclude_keys
---> 78 super().__init__(
     79     dataset,
     80     batch_size,
     81     shuffle,
     82     collate_fn=Collater(follow_batch, exclude_keys),
     83     **kwargs,
     84 )

File ~/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch/utils/data/dataloader.py:277, in DataLoader.__init__(self, dataset, batch_size, shuffle, sampler, batch_sampler, num_workers, collate_fn, pin_memory, drop_last, timeout, worker_init_fn, multiprocessing_context, generator, prefetch_factor, persistent_workers)
    275 else:  # map-style
    276     if shuffle:
--> 277         sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
    278     else:
    279         sampler = SequentialSampler(dataset)  # type: ignore[arg-type]

File ~/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch/utils/data/sampler.py:97, in RandomSampler.__init__(self, data_source, replacement, num_samples, generator)
     93     raise TypeError("replacement should be a boolean value, but got "
     94                     "replacement={}".format(self.replacement))
     96 if not isinstance(self.num_samples, int) or self.num_samples <= 0:
---> 97     raise ValueError("num_samples should be a positive integer "
     98                      "value, but got num_samples={}".format(self.num_samples))

ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by gcroci2** [comment]
> Do you have a stack trace?

```
============================================== short test summary info ===============================================
FAILED tests/test_preprocess.py::test_preprocess - TypeError: cannot pickle 'module' object
================================================= 1 failed in 2.92s ==================================================
Exception ignored in: <function PreProcessor.__del__ at 0x152102200>
Traceback (most recent call last):
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/preprocess.py", line 181, in __del__
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/preprocess.py", line 177, in shutdown
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/preprocess.py", line 49, in stop
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/process.py", line 148, in join
AssertionError: can only join a started process
```

**Comment by gcroci2** [comment]
and also:

```
====================================================== FAILURES ======================================================
__________________________________________________ test_preprocess ___________________________________________________

    def test_preprocess():
        """
        Tests preprocessing several PDB files into their feature representation HDF5 file.
    
        NB: This test sometimes fails, especially on Mac OSX. The PreProcessor class relies on python multiprocessing
        library's Queue. We need to check whether the queue is empty, which is not always reliable, the only working
        implementation on Mac OSX is really not reliable.
        """
    
        output_directory = mkdtemp()
    
        prefix = os.path.join(output_directory, "test-preprocess")
    
        preprocessor = PreProcessor([deeprank_gnn.feature.sasa], prefix, 10)
        try:
>           preprocessor.start()

tests/test_preprocess.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
deeprank_gnn/preprocess.py:121: in start
    process.start()
../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/context.py:224: in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/context.py:284: in _Popen
    return Popen(process_obj)
../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <_PreProcess name='_PreProcess-1' parent=80645 initial daemon>, file = <_io.BytesIO object at 0x1530cfdd0>
protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       TypeError: cannot pickle 'module' object

../../../../../miniforge3/envs/3d_vac/lib/python3.10/multiprocessing/reduction.py:60: TypeError
```
