### ISSUE TITLE
IndexError when running NeuralNet.train()

### ISSUE THREAD

**Issue by svenvanderburg** [DeepRank/deeprank-gnn-2#89]
When running NeuralNet.train(), @DTRademaker gets:
```python
the threshold for accuracy computation is set to 1
   Checking dataset Integrity
   Processing data set
   Train dataset         : 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.02it/s, mol=dataset.hdf5]
Loading clusters
  0%|                                                                                                      | 0/400 [00:00<?, ?it/s]no clustering group found
  0%|                                                                                                      | 0/400 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "first_net.py", line 11, in <module>
    nn = NeuralNet(database, GINet,
  File "/home/daniel/binding_project/deeprank-gnn-2/deeprank_gnn/NeuralNet.py", line 116, in __init__
    self.load_model(database, Net, database_eval)
  File "/home/daniel/binding_project/deeprank-gnn-2/deeprank_gnn/NeuralNet.py", line 186, in load_model
    PreCluster(dataset, method=self.cluster_nodes)
  File "/home/daniel/binding_project/deeprank-gnn-2/deeprank_gnn/DataSet.py", line 89, in PreCluster
    data = community_pooling(cluster, data)
  File "/home/daniel/binding_project/deeprank-gnn-2/deeprank_gnn/community_pooling.py", line 206, in community_pooling
    internal_edge_index, internal_edge_attr = pool_edge(
  File "/home/daniel/.local/lib/python3.8/site-packages/torch_geometric/nn/pool/pool.py", line 13, in pool_edge
    edge_index, edge_attr = remove_self_loops(edge_index, edge_attr)
  File "/home/daniel/.local/lib/python3.8/site-packages/torch_geometric/utils/loop.py", line 42, in remove_self_loops
    return edge_index, edge_attr[mask]
IndexError: The shape of the mask [0] at index 0 does not match the shape of the indexed tensor [2378, 0] at index 0
```
The code to reproduce this:
```python
from deeprank_gnn.NeuralNet import NeuralNet
from ginet import GINet
from deeprank_gnn.models.metrics import OutputExporter, ScatterPlotExporter

database = '/home/daniel/binding_project/outputAll/dataset.hdf5'

metrics_output_directory = "./metrics"
metrics_exporters = [OutputExporter(metrics_output_directory),
                     ScatterPlotExporter(metrics_output_directory, 5)]

nn = NeuralNet(database, GINet,
               node_feature=['hb_acceptors',
							'hb_donors',
							'polarity',
							'pos',
							'size',
							'type'],
               edge_feature=[],
               target='labels',
               task = 'class',
               index=range(400),
               batch_size=64,
               percent=[0.8, 0.2],
               metrics_exporters=metrics_exporters)

nn.train(nepoch=50, validate=False)
```

(I am still working on getting the actual dataset)

**Comment by cbaakman** [comment]
This seems to be happening during the clustering step.

**Comment by NicoRenaud** [comment]
I guess if we have only one cluster left there will be no edges anymore. I would check the number of clusters left

**Comment by cbaakman** [comment]
In the last class diagram, we merged the "edges" and "internal edges" collections into "edges". We could let the clustering software use "edges" instead.

**Comment by svenvanderburg** [comment]
OK, and that's it? For the rest the internal edges are not needed? 
And will it still make sense from deep learning perspective?

**Comment by cbaakman** [comment]
> OK, and that's it? For the rest the internal edges are not needed? And will it still make sense from deep learning perspective?

You'd be clustering based on proximity between nodes. It would make less sense than clustering only on internal edges, which usually represent covalent bonds. If clustering is this important then we do maybe need to take only the edges with the covalent feature set to True.
